/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Completion: () => import('#controllers/completion_controller'),
  user: {
    NewAccount: () => import('#controllers/user/new_account_controller'),
    Session: () => import('#controllers/user/session_controller'),
  },
}
